version: "3.8"

services:
  api:
    build:
      context: ./docker/api
    container_name: gerencia_extintor_api
    ports:
      - 3333:80
    volumes:
      - ./api:/api/app
      - ./docs/api:/api/docs
      - ./docker/api/scripts:/api/scripts
    working_dir: /api
    command: ./scripts/prepareContainer.sh

  web:
    build:
      context: ./docker/web
    container_name: gerencia_extintor_web
    ports:
      - 3000:80
    volumes:
      - ./web:/web/app
      - ./docs/web:/web/docs
      - ./docker/web/scripts:/web/scripts
    working_dir: /web
    command: ./scripts/prepareContainer.sh
